# Generated by Django 5.0.6 on 2024-05-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_quanitiy_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryLogo',
            field=models.ImageField(blank=True, null=True, upload_to='media/category logos/'),
        ),
    ]
