# Generated by Django 5.0.6 on 2024-05-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_categorylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryLogo',
            field=models.ImageField(blank=True, null=True, upload_to='category logos/'),
        ),
    ]
