# Generated by Django 5.0.6 on 2024-06-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryLogo',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
